apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  annotations:
   argocd.argoprojct.io/sync-wave: "0"

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_PASSWORD

          ports:
            - containerPort: 3306

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc