---
# Source: backend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
---
# Source: backend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm

spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: backend

  template:
    metadata:

      labels:
        helm.sh/chart: backend-0.1.0
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: backend
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm

    spec:

      serviceAccountName: backend

      containers:
        - name: backend

          image: "163053485065.dkr.ecr.ap-south-1.amazonaws.com/skillpulse-backend:latest"

          imagePullPolicy: Always

          env:
            - name: DB_HOST
              value: mysql.skillpulse.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: skillpulse
            - name: DB_PASSWORD
              value: skillpulse123
            - name: DB_NAME
              value: skillpulse
            - name: PORT
              value: "8080"

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: backend/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "backend-test-connection"
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['backend:80']
  restartPolicy: Never
