replicaCount: 1

image:
  repository: srini2390/skillpulse-backend
  tag: "d31f8052006a39e9f5894922d82c351ffe632fb1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    memory: 256Mi