replicaCount: 1

image:
  repository: srini2390/skillpulse-backend
  tag: "a7d758ec1386e1c72fdbaa90c8fd127c57af7e46"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    memory: 256Mi