replicaCount: 1

image:
  repository: srini2390/skillpulse-backend
  tag: "8ec3478e4e3377f077440617bf4cae41e7da3702"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    memory: 256Mi