name: CI Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build temporary image for scanning
      - name: Build Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          load: true
          tags: skillpulse-backend:scan

      # Trivy vulnerability scan
      - name: Run Trivy Scan Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: skillpulse-backend:scan
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Push only if scan passes
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            srini2390/skillpulse-backend:latest
            srini2390/skillpulse-backend:${{ github.sha }}

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build temporary image for scanning
      - name: Build Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          load: true
          tags: skillpulse-frontend:scan

      # Trivy vulnerability scan
      - name: Run Trivy Scan Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: skillpulse-frontend:scan
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Push only if scan passes
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            srini2390/skillpulse-frontend:latest
            srini2390/skillpulse-frontend:${{ github.sha }}