replicaCount: 1

image:
  repository: srini2390/skillpulse-frontend
  tag: "CURRENT_TAG"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 32Mi

  limits:
    memory: 64Mi