replicaCount: 1

image:
  repository: srini2390/skillpulse-frontend
  tag: 2b19d0757dea624a5560ec7eb913e0d3d3e61447
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 50m
    memory: 32Mi

  limits:
    memory: 64Mi