replicaCount: 1

image:
  repository: srini2390/skillpulse-frontend
  tag: 8ec3478e4e3377f077440617bf4cae41e7da3702
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 32Mi

  limits:
    memory: 64Mi